//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DmLaboratorij_1.Views.Shared
{
    using System;
    using System.Collections.Generic;
    
    public partial class userInfo
    {
        public int ID { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Email { get; set; }
        public string HomeTown { get; set; }
        public string Likes { get; set; }
        public string RelationshipStatus { get; set; }
        public string Birthday { get; set; }
        public string UserFriends { get; set; }
        public string AccessToken { get; set; }
    }
}
